version: "3.4"

services:
  twitter-pooler-db:
    image: "mongo:latest"
    container_name: twitter-pooler-db
    expose:
      - 27017
    networks:
      - twitter

  twitterpooler:
    container_name: twitterpooler
    image: "twitter-pooler:latest"
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - "8085:8080"
    links:
      - twitter-pooler-db
    depends_on:
      - twitter-pooler-db
    networks:
        - twitter

networks:
  twitter:
    driver: bridge
